//Tables
GRANT ALL ON ANIMAL_TYPE TO mlh395;
GRANT ALL ON ANIMAL_SUBTYPE TO mlh395;
GRANT ALL ON KENNEL TO mlh395;
GRANT ALL ON ANIMAL_DETAIL TO mlh395;
GRANT ALL ON ANIMAL TO mlh395;
GRANT ALL ON BEHAVIOR TO mlh395;
GRANT ALL ON ANIMAL_BEHAVIOR TO mlh395;
GRANT ALL ON EMPLOYEE TO mlh395;
GRANT ALL ON ADOPTION TO mlh395;
GRANT ALL ON TASK TO mlh395;
GRANT ALL ON TASK_LOG TO mlh395;
GRANT ALL ON ANIMAL_TRAINING TO mlh395;

//Views
GRANT ALL ON employee_training TO mlh395;
GRANT ALL ON tasks_to_do TO mlh395;
GRANT ALL ON available_animals TO mlh395;
GRANT ALL ON kennel_capacity TO mlh395;

//Functions & Procedures
GRANT EXECUTE ON add_animal TO mlh395;
GRANT EXECUTE ON convertWeight TO mlh395;
GRANT EXECUTE ON animal_size TO mlh395;